const fs = require('fs');
const path = require('path');

const dir = 'C:/Users/Johnmary/Downloads/ANTIGRAVITY/FETZY';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.html'));

let fixCount = 0;

files.forEach(file => {
    let content = fs.readFileSync(path.join(dir, file), 'utf8');
    let hasChanges = false;

    // 1. Global Contrast Upgrades
    // Replace hard-to-read grey on dark backgrounds
    const contrastMap = [
        { from: /text-slate-600/g, to: 'text-slate-400' },
        { from: /text-slate-500/g, to: 'text-slate-400' },
        { from: /dark:text-slate-400/g, to: 'dark:text-slate-300' },
        { from: /dark:text-slate-500/g, to: 'dark:text-slate-300' },
        { from: /dark:text-slate-600/g, to: 'dark:text-slate-400' }
    ];

    contrastMap.forEach(pair => {
        if (content.match(pair.from)) {
            content = content.replace(pair.from, pair.to);
            hasChanges = true;
        }
    });

    // 2. Padding Repair (About Page & Cards)
    if (content.includes('Vision') || content.includes('Mission')) {
        // Upgrade p-6 to p-10 for premium breathing room
        content = content.replace(/class="([^"]*)\bp-6\b([^"]*)"/g, 'class="$1p-10$2"');
        hasChanges = true;
    }

    // 3. Service Card Alignment (services.html)
    if (file === 'services.html') {
        // Find service card containers and ensure they are h-full flex columns
        // This targets the specific structure generated by Stitch
        content = content.replace(/class="([^"]*bg-white[^"]*rounded-2xl[^"]*)"/g, (match, p1) => {
            if (!p1.includes('flex-col')) return `class="${p1} flex flex-col h-full"`;
            return match;
        });
        // Push buttons to the bottom
        content = content.replace(/<a([^>]*class="[^"]*bg-primary[^"]*)"/g, (match, p1) => {
            if (!p1.includes('mt-auto')) return `<a${p1} mt-auto"`;
            return match;
        });
        hasChanges = true;
    }

    // 4. Process Timeline Repair (process.html)
    if (file === 'process.html') {
        // Target the material icons sitting on the line
        // We wrap them in a styled div that creates a 'break' in the timeline line
        content = content.replace(/<span class="material-symbols-outlined([^"]*)">([^<]+)<\/span>/g, (match, p1, p2) => {
            const icons = ['edit_note', 'inventory_2', 'construction', 'verified', 'handshake'];
            if (icons.includes(p2.trim())) {
                return `<div class="w-12 h-12 rounded-full bg-primary flex items-center justify-center text-background-dark shadow-xl z-20 border-4 border-background-dark relative"><span class="material-symbols-outlined${p1}">${p2}</span></div>`;
            }
            return match;
        });
        hasChanges = true;
    }

    // 5. Restore Link Connectivity (Anti-dead-link)
    // Replace index.html links in sub-pages that should point to themselves or other logical pages
    if (file !== 'index.html') {
        // If a "Learn More" or "Read More" button points to index.html, it's likely a breakdown
        // We change these to point to the current file or specific details
        // Note: Global repair already happened, this is surgical for the 'premium' look
        content = content.replace(/href="index\.html"([^>]*>View Details|[^>]*>Learn More|[^>]*>Explore)/g, `href="${file}"$1`);
        hasChanges = true;
    }

    if (hasChanges) {
        fs.writeFileSync(path.join(dir, file), content);
        fixCount++;
        console.log(`[FIXED] Design & formatting in ${file}`);
    }
});

console.log(`\nTypography and Layout refinement completed for ${fixCount} pages.`);
